### ISSUE TITLE
hist_YieldCurve(Hist) returns error when applied from the command line

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/RPC#24]
setwd("C:/GitHub/EGB_Haddock_RefPts") 
Hist = readRDS("./OMs/Assessment_2022/Hist_H.rda") # Hist object made by runMSE(OM,Hist=T)
hist_YieldCurve(Hist)

Error in MSEtool:::MSYCalcs(y, M_at_Age = M[x, ], Wt_at_Age = Wt_age[x,  : 
  argument "relRfun" is missing, with no default

**Comment by quang-huynh** [comment]
RPC uses some internal MSEtool functions that have since been updated and no longer compatible. Using an old version without the custom SRR will work for now
