### ISSUE TITLE
Not a big deal, but some RPC plots are rather slow to render (nsim = 200)

### ISSUE THREAD

**Issue by tcarruth** [Blue-Matter/RPC#27]
hist_SRR_change(Hist)  # very slow
hist_per_recruit(Hist)    # slowish
hist_YieldCurve(Hist)    # slow
LRP_50Rmax(Hist)        # very slow
LRP_RPS90(Hist)           # very slow

some of these appear to be faster with a graphics device (e.g. jpeg())

**Comment by quang-huynh** [comment]
hist_SRR_change, LRP_50Rmax, LRP_RPS90 plot all individual SSB-R points. The new default plots a smaller subset of simulations and should be quicker: hist_SRR_change(sims = 1:25)

hist_per_recruit and hist_YieldCurve calculates from a grid of simulations and F using MSEtool:::MSYCalcs. The sims argument is also added here but the default does no subsetting
